# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: docker login
      env:
        CCC_DOCKER_USER: ${{ secrets.CCC_DOCKER_USER }}
        CCC_DOCKER_PASS: ${{ secrets.CCC_DOCKER_PASS }}
      run: echo "$CCC_DOCKER_PASS" | docker login -u "$CCC_DOCKER_USER" --password-stdin

    - name: Build ccc-service.jar
      run: ./gradlew build
    - name: Build and test image
      run: ./gradlew testImage

    - name: push image to docker hub
      run: ./gradlew pushImage
