name: Release Docker Image

on:
  release:
    types: [ published ]

jobs:
  ci-and-release:
    uses: ./.github/workflows/ci.yml
    with:
      release_tag: ${{ github.event.release.tag_name }}
    secrets: inherit
